project_id = "rzzzfprgnoywmmjwepzm"

[functions.analisar-sentimento-cliente]
verify_jwt = true

[functions.chat-assistente-ticket]
verify_jwt = true

[functions.chat-assistente-criacao]
verify_jwt = true

[functions.classificar-criticidade-ticket]
verify_jwt = true

[functions.gupshup-enviar-mensagem]
verify_jwt = false

[functions.gupshup-webhook]
verify_jwt = false

[functions.handle-ura-zenvia]
verify_jwt = false